// generators.js – Pure functions that produce Minecraft Bedrock JSON/text

function genUUID() {
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, c => {
    const r = Math.random() * 16 | 0;
    return (c === 'x' ? r : (r & 0x3 | 0x8)).toString(16);
  });
}

function resolveId(identifier, namespace) {
  return identifier.includes(':') ? identifier : `${namespace}:${identifier}`;
}

// ── MANIFESTS ──────────────────────────────────────────────────────────────

function generateManifestBP(project) {
  return {
    format_version: 2,
    header: {
      name: (project.name || 'My Addon') + ' - Behavior Pack',
      description: project.description || 'Behavior pack generated by MC Mod Creator',
      uuid: genUUID(),
      version: project.version || [1, 0, 0],
      min_engine_version: [1, 20, 0]
    },
    modules: [{
      type: 'data',
      uuid: genUUID(),
      version: [1, 0, 0]
    }]
  };
}

function generateManifestRP(project) {
  return {
    format_version: 2,
    header: {
      name: (project.name || 'My Addon') + ' - Resource Pack',
      description: project.description || 'Resource pack generated by MC Mod Creator',
      uuid: genUUID(),
      version: project.version || [1, 0, 0],
      min_engine_version: [1, 20, 0]
    },
    modules: [{
      type: 'resources',
      uuid: genUUID(),
      version: [1, 0, 0]
    }]
  };
}

// ── ITEMS ──────────────────────────────────────────────────────────────────

function generateItemBP(item, namespace) {
  const id = resolveId(item.identifier, namespace);

  const categoryMap = {
    Items: 'items', Nature: 'nature',
    Equipment: 'equipment', Construction: 'construction', Command: 'none'
  };

  const texName = id.replace(':', '_');

  const components = {
    'minecraft:max_stack_size': Math.min(64, Math.max(1, parseInt(item.maxStackSize) || 1)),
    'minecraft:icon': { texture: texName }
  };

  if (item.isWeapon) {
    if (parseInt(item.damage) > 0) {
      components['minecraft:damage'] = parseInt(item.damage);
    }
    if (parseInt(item.durability) > 0) {
      components['minecraft:durability'] = { max_durability: parseInt(item.durability) };
    }
  }

  if (item.isFood) {
    const food = {
      nutrition: parseInt(item.nutrition) || 4,
      saturation_modifier: item.saturationModifier || 'normal'
    };
    if (item.canAlwaysEat) food.can_always_eat = true;
    components['minecraft:food'] = food;
  }

  if (item.isFoil || item.isGlint) {
    components['minecraft:glint'] = true;
  }

  if (item.isThrowable) {
    components['minecraft:throwable'] = { do_swing_animation: true, launch_power_scale: 1.0, max_launch_power: 1.0 };
    components['minecraft:projectile'] = { projectile_entity: 'minecraft:snowball', minimum_critical_power: 1.0 };
  }

  if (item.handEquipped) {
    components['minecraft:hand_equipped'] = true;
  }

  return {
    format_version: '1.20.10',
    'minecraft:item': {
      description: {
        identifier: id,
        menu_category: { category: categoryMap[item.category] || 'items' }
      },
      components
    }
  };
}

// ── BLOCKS ─────────────────────────────────────────────────────────────────

function generateBlockBP(block, namespace) {
  const id = resolveId(block.identifier, namespace);
  const textureName = id.replace(':', '_');

  const categoryMap = {
    Construction: 'construction', Nature: 'nature',
    Items: 'items', Equipment: 'equipment'
  };

  const components = {};

  const hardness = parseFloat(block.hardness);
  if (hardness >= 0) {
    components['minecraft:destructible_by_mining'] = { seconds_to_destroy: hardness };
  } else {
    // Indestructible
    components['minecraft:destructible_by_mining'] = false;
  }

  components['minecraft:destructible_by_explosion'] = {
    explosion_resistance: parseFloat(block.resistance) || 6.0
  };

  components['minecraft:friction'] = parseFloat(block.friction) || 0.6;

  if (block.isFlammable) {
    components['minecraft:flammable'] = {
      catch_chance_modifier: parseInt(block.flamOdds) || 5,
      destroy_chance_modifier: parseInt(block.burnOdds) || 20
    };
  }

  if (block.mapColor) {
    components['minecraft:map_color'] = block.mapColor;
  }

  const lightEmission = parseInt(block.lightEmission) || 0;
  if (lightEmission > 0) {
    components['minecraft:light_emission'] = lightEmission;
  }

  const lightDampening = parseInt(block.lightDampening);
  if (!isNaN(lightDampening)) {
    components['minecraft:light_dampening'] = lightDampening;
  }

  components['minecraft:geometry'] = 'minecraft:geometry.full_block';

  components['minecraft:material_instances'] = {
    '*': {
      texture: textureName,
      render_method: block.isTransparent ? 'blend' : 'opaque'
    }
  };

  return {
    format_version: '1.20.10',
    'minecraft:block': {
      description: {
        identifier: id,
        menu_category: { category: categoryMap[block.category] || 'construction' }
      },
      components
    }
  };
}

// ── ENTITIES ───────────────────────────────────────────────────────────────

function generateEntityBP(entity, namespace) {
  const id = resolveId(entity.identifier, namespace);

  const components = {
    'minecraft:type_family': {
      family: entity.isHostile ? ['monster', 'mob'] : ['mob', 'animal']
    },
    'minecraft:health': {
      value: parseInt(entity.health) || 20,
      max: parseInt(entity.health) || 20
    },
    'minecraft:movement': {
      value: parseFloat(entity.movementSpeed) || 0.25
    },
    'minecraft:collision_box': {
      width: parseFloat(entity.collisionWidth) || 0.6,
      height: parseFloat(entity.collisionHeight) || 1.8
    },
    'minecraft:navigation.walk': {
      can_path_over_water: true,
      avoid_water: !entity.swimsInWater
    },
    'minecraft:movement.basic': {},
    'minecraft:jump.static': {},
    'minecraft:breathable': {
      breathes_air: true,
      breathes_water: !!entity.swimsInWater,
      total_supply: 15,
      suffocate_time: -1
    },
    'minecraft:physics': {},
    'minecraft:behavior.look_at_player': { priority: 7, look_distance: 8 },
    'minecraft:behavior.random_look_around': { priority: 8 },
    'minecraft:behavior.random_stroll': { priority: 6, speed_multiplier: 1.0 }
  };

  if (entity.isHostile) {
    components['minecraft:attack'] = { damage: parseInt(entity.attackDamage) || 3 };
    components['minecraft:behavior.melee_attack'] = { priority: 3 };
    components['minecraft:behavior.nearest_attackable_target'] = {
      priority: 2,
      entity_types: [{
        filters: { test: 'is_family', subject: 'other', value: 'player' }
      }]
    };
  }

  if (entity.isTameable) {
    components['minecraft:tameable'] = {
      probability: 0.33,
      tame_items: ['minecraft:bone'],
      tame_event: { event: 'minecraft:on_tame', target: 'self' }
    };
    components['minecraft:behavior.follow_owner'] = {
      priority: 4,
      speed_multiplier: 1.0,
      start_distance: 10.0,
      stop_distance: 2.0
    };
  }

  if (entity.swimsInWater) {
    components['minecraft:underwater_movement'] = { value: parseFloat(entity.movementSpeed) * 0.5 || 0.12 };
    components['minecraft:navigation.swim'] = { can_path_over_water: true };
  }

  if (parseInt(entity.dropsXP) > 0) {
    components['minecraft:experience_reward'] = {
      on_death: `query.last_hit_by_player ? ${entity.dropsXP} : 0`
    };
  }

  if (parseFloat(entity.knockbackResist) > 0) {
    components['minecraft:knockback_resistance'] = {
      value: parseFloat(entity.knockbackResist)
    };
  }

  return {
    format_version: '1.20.10',
    'minecraft:entity': {
      description: {
        identifier: id,
        is_spawnable: entity.isSpawnable !== false,
        is_summonable: true,
        is_experimental: false
      },
      component_groups: {},
      components,
      events: {}
    }
  };
}

// ── ENTITY RESOURCE PACK ───────────────────────────────────────────────────

function generateEntityGeometry(entity, namespace) {
  const id = resolveId(entity.identifier, namespace);
  const geoId = `geometry.${id.replace(':', '_')}`;
  const is32h = entity.bodyType === 'quadruped' || entity.bodyType === 'bird' || entity.bodyType === 'slime';
  const tw = 64, th = is32h ? 32 : 64;

  let bones = [];
  switch (entity.bodyType) {
    case 'quadruped':
      bones = [
        { name: 'root', pivot: [0, 0, 0] },
        { name: 'body', parent: 'root', pivot: [0, 10, 0],
          cubes: [{ origin: [-5, 6, -10], size: [10, 8, 16], uv: [28, 8] }] },
        { name: 'head', parent: 'body', pivot: [0, 12, -8],
          cubes: [{ origin: [-4, 8, -14], size: [8, 8, 8], uv: [0, 0] }] },
        { name: 'leg0', parent: 'root', pivot: [-3, 6, -5],
          cubes: [{ origin: [-5, 0, -7], size: [4, 6, 4], uv: [0, 16] }] },
        { name: 'leg1', parent: 'root', pivot: [3, 6, -5],
          cubes: [{ origin: [1, 0, -7], size: [4, 6, 4], uv: [0, 16] }] },
        { name: 'leg2', parent: 'root', pivot: [-3, 6, 5],
          cubes: [{ origin: [-5, 0, 3], size: [4, 6, 4], uv: [0, 16] }] },
        { name: 'leg3', parent: 'root', pivot: [3, 6, 5],
          cubes: [{ origin: [1, 0, 3], size: [4, 6, 4], uv: [0, 16] }] }
      ];
      break;
    case 'bird':
      bones = [
        { name: 'root', pivot: [0, 0, 0] },
        { name: 'body', parent: 'root', pivot: [0, 8, 0],
          cubes: [{ origin: [-3, 4, -3], size: [6, 8, 6], uv: [20, 0] }] },
        { name: 'head', parent: 'body', pivot: [0, 12, 0],
          cubes: [{ origin: [-2, 12, -2], size: [4, 4, 4], uv: [0, 0] }] },
        { name: 'beak', parent: 'head', pivot: [0, 12, -2],
          cubes: [{ origin: [-1, 11, -4], size: [2, 2, 2], uv: [14, 0] }] },
        { name: 'leg0', parent: 'root', pivot: [-1, 4, 0],
          cubes: [{ origin: [-2, 0, -1], size: [2, 4, 2], uv: [0, 8] }] },
        { name: 'leg1', parent: 'root', pivot: [1, 4, 0],
          cubes: [{ origin: [0, 0, -1], size: [2, 4, 2], uv: [8, 8] }] },
        { name: 'wing0', parent: 'body', pivot: [-3, 11, 0],
          cubes: [{ origin: [-5, 9, -2], size: [2, 4, 4], uv: [34, 0] }] },
        { name: 'wing1', parent: 'body', pivot: [3, 11, 0],
          cubes: [{ origin: [3, 9, -2], size: [2, 4, 4], uv: [44, 0] }] }
      ];
      break;
    case 'slime':
      bones = [
        { name: 'root', pivot: [0, 0, 0] },
        { name: 'body', parent: 'root', pivot: [0, 0, 0],
          cubes: [{ origin: [-4, 0, -4], size: [8, 8, 8], uv: [0, 0] }] },
        { name: 'eyes', parent: 'body', pivot: [0, 0, 0],
          cubes: [
            { origin: [-3, 4, -5], size: [2, 2, 1], uv: [32, 0] },
            { origin: [1, 4, -5],  size: [2, 2, 1], uv: [32, 0] }
          ] }
      ];
      break;
    case 'bat':
      bones = [
        { name: 'root', pivot: [0, 24, 0] },
        { name: 'body', parent: 'root', pivot: [0, 24, 0],
          cubes: [{ origin: [-3, 17, -2], size: [6, 9, 4], uv: [0, 16] }] },
        { name: 'head', parent: 'body', pivot: [0, 24, 0],
          cubes: [{ origin: [-3, 22, -3], size: [6, 6, 6], uv: [0, 0] }] },
        { name: 'wing0', parent: 'body', pivot: [-3, 24, 0],
          cubes: [{ origin: [-15, 15, 0], size: [12, 16, 1], uv: [22, 0] }] },
        { name: 'wing1', parent: 'body', pivot: [3, 24, 0],
          cubes: [{ origin: [3, 15, 0], size: [12, 16, 1], uv: [22, 0] }] }
      ];
      break;
    case 'undead':
    case 'humanoid':
    default:
      bones = [
        { name: 'root', pivot: [0, 0, 0] },
        { name: 'body', parent: 'root', pivot: [0, 24, 0],
          cubes: [{ origin: [-4, 12, -2], size: [8, 12, 4], uv: [16, 16] }] },
        { name: 'head', parent: 'body', pivot: [0, 24, 0],
          cubes: [{ origin: [-4, 24, -4], size: [8, 8, 8], uv: [0, 0] }] },
        { name: 'rightArm', parent: 'body', pivot: [-5, 22, 0],
          cubes: [{ origin: [-8, 12, -2], size: [4, 12, 4], uv: [40, 16] }] },
        { name: 'leftArm', parent: 'body', pivot: [5, 22, 0],
          cubes: [{ origin: [4, 12, -2], size: [4, 12, 4], uv: [32, 48] }] },
        { name: 'rightLeg', parent: 'root', pivot: [-1.9, 12, 0],
          cubes: [{ origin: [-4, 0, -2], size: [4, 12, 4], uv: [0, 16] }] },
        { name: 'leftLeg', parent: 'root', pivot: [1.9, 12, 0],
          cubes: [{ origin: [0, 0, -2], size: [4, 12, 4], uv: [16, 48] }] }
      ];
  }

  return {
    format_version: '1.12.0',
    'minecraft:geometry': [{
      description: {
        identifier: geoId,
        texture_width: tw,
        texture_height: th,
        visible_bounds_width: 2,
        visible_bounds_height: 2,
        visible_bounds_offset: [0, 1, 0]
      },
      bones
    }]
  };
}

function generateEntityClientEntity(entity, namespace) {
  const id = resolveId(entity.identifier, namespace);
  const texName = id.replace(':', '_');
  const geometry = `geometry.${id.replace(':', '_')}`;

  const description = {
    identifier: id,
    materials: { default: 'entity_alphatest' },
    textures: { default: `textures/entity/${texName}` },
    geometry: { default: geometry },
    render_controllers: ['controller.render.default'],
    spawn_egg: {
      base_color: entity.color || '#888888',
      overlay_color: entity.color2 || '#444444'
    }
  };

  return {
    format_version: '1.10.0',
    'minecraft:client_entity': { description }
  };
}

// ── RECIPES ────────────────────────────────────────────────────────────────

function generateRecipeBP(recipe, namespace) {
  const id = resolveId(recipe.identifier, namespace);

  if (recipe.type === 'shaped') {
    const grid = recipe.pattern || [['','',''],['','',''],['','','']];
    const itemToKey = {};
    const key = {};
    const letters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
    let idx = 0;

    for (const row of grid) {
      for (const cell of row) {
        const c = (cell || '').trim();
        if (c && !itemToKey[c]) {
          itemToKey[c] = letters[idx++];
          key[itemToKey[c]] = { item: c };
        }
      }
    }

    const pattern = grid.map(row =>
      row.map(cell => {
        const c = (cell || '').trim();
        return c ? itemToKey[c] : ' ';
      }).join('')
    );

    // Trim trailing empty rows
    let last = -1;
    for (let i = pattern.length - 1; i >= 0; i--) {
      if (pattern[i].trim()) { last = i; break; }
    }
    const trimmedPattern = last >= 0 ? pattern.slice(0, last + 1) : [' '];

    return {
      format_version: '1.17.41',
      'minecraft:recipe_shaped': {
        description: { identifier: id },
        tags: ['crafting_table'],
        pattern: trimmedPattern,
        key,
        result: {
          item: recipe.result || 'minecraft:air',
          count: parseInt(recipe.resultCount) || 1
        }
      }
    };

  } else if (recipe.type === 'shapeless') {
    const ingredients = (recipe.ingredients || []).filter(i => (i || '').trim());
    return {
      format_version: '1.17.41',
      'minecraft:recipe_shapeless': {
        description: { identifier: id },
        tags: ['crafting_table'],
        ingredients: ingredients.map(item => ({ item })),
        result: {
          item: recipe.result || 'minecraft:air',
          count: parseInt(recipe.resultCount) || 1
        }
      }
    };

  } else if (recipe.type === 'smelting') {
    return {
      format_version: '1.17.41',
      'minecraft:recipe_furnace': {
        description: { identifier: id },
        tags: [recipe.smeltingType || 'furnace'],
        input: { item: recipe.input || 'minecraft:air' },
        output: recipe.result || 'minecraft:air'
      }
    };
  }

  return null;
}

// ── ITEM RESOURCE PACK ─────────────────────────────────────────────────────

function generateItemRP(item, namespace) {
  const id = resolveId(item.identifier, namespace);
  const texName = id.replace(':', '_');

  const categoryMap = {
    Items: 'Items', Nature: 'Nature',
    Equipment: 'Equipment', Construction: 'Construction', Command: 'none'
  };

  return {
    format_version: '1.10.0',
    'minecraft:item': {
      description: {
        identifier: id,
        category: categoryMap[item.category] || 'Items'
      },
      components: {
        'minecraft:icon': {
          texture: texName
        }
      }
    }
  };
}

// ── RESOURCE PACK HELPERS ─────────────────────────────────────────────────

function generateTerrainTexture(blocks, namespace, packName) {
  const texture_data = {};
  for (const block of blocks) {
    const id = resolveId(block.identifier, namespace);
    const texName = id.replace(':', '_');
    texture_data[texName] = { textures: `textures/blocks/${texName}` };
  }
  return {
    resource_pack_name: packName || 'vanilla',
    texture_name: 'atlas.terrain',
    padding: 8,
    num_mip_levels: 4,
    texture_data
  };
}

function generateItemTexture(items, namespace, packName) {
  const texture_data = {};
  for (const item of items) {
    const id = resolveId(item.identifier, namespace);
    const texName = id.replace(':', '_');
    texture_data[texName] = { textures: `textures/items/${texName}` };
  }
  return {
    resource_pack_name: packName || 'vanilla',
    texture_name: 'atlas.items',
    texture_data
  };
}

function generateLangFile(items, blocks, entities, namespace) {
  const lines = [];
  for (const item of items) {
    const id = resolveId(item.identifier, namespace);
    const name = item.displayName || id.split(':').pop();
    lines.push(`item.${id}.name=${name}`);
  }
  for (const block of blocks) {
    const id = resolveId(block.identifier, namespace);
    const name = block.displayName || id.split(':').pop();
    lines.push(`tile.${id}.name=${name}`);
  }
  for (const entity of entities) {
    const id = resolveId(entity.identifier, namespace);
    const name = entity.displayName || id.split(':').pop();
    lines.push(`entity.${id}.name=${name}`);
  }
  return lines.join('\n');
}

// ── SYNTAX HIGHLIGHTING ────────────────────────────────────────────────────

function syntaxHighlight(json) {
  if (typeof json !== 'string') {
    json = JSON.stringify(json, null, 2);
  }
  return json
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(
      /("(\\u[a-zA-Z0-9]{4}|\\[^u]|[^\\"])*"(\s*:)?|\b(true|false|null)\b|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)/g,
      match => {
        let cls = 'json-num';
        if (/^"/.test(match)) {
          cls = /:$/.test(match) ? 'json-key' : 'json-str';
        } else if (/true|false/.test(match)) {
          cls = 'json-bool';
        } else if (/null/.test(match)) {
          cls = 'json-null';
        }
        return `<span class="${cls}">${match}</span>`;
      }
    );
}
