// generators.js – Pure functions that produce Minecraft Bedrock JSON/text

function genUUID() {
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, c => {
    const r = Math.random() * 16 | 0;
    return (c === 'x' ? r : (r & 0x3 | 0x8)).toString(16);
  });
}

function resolveId(identifier, namespace) {
  return identifier.includes(':') ? identifier : `${namespace}:${identifier}`;
}

// ── MANIFESTS ──────────────────────────────────────────────────────────────

function generateManifestBP(project) {
  return {
    format_version: 2,
    header: {
      name: (project.name || 'My Addon') + ' - Behavior Pack',
      description: project.description || 'Behavior pack generated by MC Mod Creator',
      uuid: genUUID(),
      version: project.version || [1, 0, 0],
      min_engine_version: [1, 20, 0]
    },
    modules: [{
      type: 'data',
      uuid: genUUID(),
      version: [1, 0, 0]
    }]
  };
}

function generateManifestRP(project) {
  return {
    format_version: 2,
    header: {
      name: (project.name || 'My Addon') + ' - Resource Pack',
      description: project.description || 'Resource pack generated by MC Mod Creator',
      uuid: genUUID(),
      version: project.version || [1, 0, 0],
      min_engine_version: [1, 20, 0]
    },
    modules: [{
      type: 'resources',
      uuid: genUUID(),
      version: [1, 0, 0]
    }]
  };
}

// ── ITEMS ──────────────────────────────────────────────────────────────────

function generateItemBP(item, namespace) {
  const id = resolveId(item.identifier, namespace);

  const categoryMap = {
    Items: 'items', Nature: 'nature',
    Equipment: 'equipment', Construction: 'construction', Command: 'none'
  };

  const components = {
    'minecraft:max_stack_size': Math.min(64, Math.max(1, parseInt(item.maxStackSize) || 64))
  };

  if (item.isWeapon) {
    if (parseInt(item.damage) > 0) {
      components['minecraft:damage'] = parseInt(item.damage);
    }
    if (parseInt(item.durability) > 0) {
      components['minecraft:durability'] = { max_durability: parseInt(item.durability) };
    }
  }

  if (item.isFood) {
    const food = {
      nutrition: parseInt(item.nutrition) || 4,
      saturation_modifier: item.saturationModifier || 'normal'
    };
    if (item.canAlwaysEat) food.can_always_eat = true;
    components['minecraft:food'] = food;
  }

  if (item.isFoil || item.isGlint) {
    components['minecraft:glint'] = true;
  }

  if (item.isThrowable) {
    components['minecraft:throwable'] = { do_swing_animation: true, launch_power_scale: 1.0, max_launch_power: 1.0 };
    components['minecraft:projectile'] = { projectile_entity: 'minecraft:snowball', minimum_critical_power: 1.0 };
  }

  if (item.handEquipped) {
    components['minecraft:hand_equipped'] = true;
  }

  return {
    format_version: '1.20.10',
    'minecraft:item': {
      description: {
        identifier: id,
        menu_category: { category: categoryMap[item.category] || 'items' }
      },
      components
    }
  };
}

// ── BLOCKS ─────────────────────────────────────────────────────────────────

function generateBlockBP(block, namespace) {
  const id = resolveId(block.identifier, namespace);
  const textureName = id.replace(':', '_');

  const categoryMap = {
    Construction: 'construction', Nature: 'nature',
    Items: 'items', Equipment: 'equipment'
  };

  const components = {};

  const hardness = parseFloat(block.hardness);
  if (hardness >= 0) {
    components['minecraft:destructible_by_mining'] = { seconds_to_destroy: hardness };
  } else {
    // Indestructible
    components['minecraft:destructible_by_mining'] = false;
  }

  components['minecraft:destructible_by_explosion'] = {
    explosion_resistance: parseFloat(block.resistance) || 6.0
  };

  components['minecraft:friction'] = parseFloat(block.friction) || 0.6;

  if (block.isFlammable) {
    components['minecraft:flammable'] = {
      catch_chance_modifier: parseInt(block.flamOdds) || 5,
      destroy_chance_modifier: parseInt(block.burnOdds) || 20
    };
  }

  if (block.mapColor) {
    components['minecraft:map_color'] = block.mapColor;
  }

  const lightEmission = parseInt(block.lightEmission) || 0;
  if (lightEmission > 0) {
    components['minecraft:light_emission'] = lightEmission;
  }

  const lightDampening = parseInt(block.lightDampening);
  if (!isNaN(lightDampening)) {
    components['minecraft:light_dampening'] = lightDampening;
  }

  components['minecraft:geometry'] = 'minecraft:geometry.full_block';

  components['minecraft:material_instances'] = {
    '*': {
      texture: textureName,
      render_method: block.isTransparent ? 'blend' : 'opaque'
    }
  };

  return {
    format_version: '1.20.10',
    'minecraft:block': {
      description: {
        identifier: id,
        menu_category: { category: categoryMap[block.category] || 'construction' }
      },
      components
    }
  };
}

// ── ENTITIES ───────────────────────────────────────────────────────────────

function generateEntityBP(entity, namespace) {
  const id = resolveId(entity.identifier, namespace);

  const components = {
    'minecraft:type_family': {
      family: entity.isHostile ? ['monster', 'mob'] : ['mob', 'animal']
    },
    'minecraft:health': {
      value: parseInt(entity.health) || 20,
      max: parseInt(entity.health) || 20
    },
    'minecraft:movement': {
      value: parseFloat(entity.movementSpeed) || 0.25
    },
    'minecraft:collision_box': {
      width: parseFloat(entity.collisionWidth) || 0.6,
      height: parseFloat(entity.collisionHeight) || 1.8
    },
    'minecraft:navigation.walk': {
      can_path_over_water: true,
      avoid_water: !entity.swimsInWater
    },
    'minecraft:movement.basic': {},
    'minecraft:jump.static': {},
    'minecraft:behavior.look_at_player': { priority: 7, look_distance: 8 },
    'minecraft:behavior.random_look_around': { priority: 8 },
    'minecraft:behavior.random_stroll': { priority: 6, speed_multiplier: 1.0 }
  };

  if (entity.isHostile) {
    components['minecraft:attack'] = { damage: parseInt(entity.attackDamage) || 3 };
    components['minecraft:behavior.melee_attack'] = { priority: 3 };
    components['minecraft:behavior.nearest_attackable_target'] = {
      priority: 2,
      entity_types: [{
        filters: { test: 'is_family', subject: 'other', value: 'player' }
      }]
    };
  }

  if (entity.isTameable) {
    components['minecraft:tameable'] = {
      probability: 0.33,
      tame_items: ['minecraft:bone'],
      tame_event: { event: 'minecraft:on_tame', target: 'self' }
    };
    components['minecraft:behavior.follow_owner'] = {
      priority: 4,
      speed_multiplier: 1.0,
      start_distance: 10.0,
      stop_distance: 2.0
    };
  }

  if (parseInt(entity.dropsXP) > 0) {
    components['minecraft:experience_reward'] = {
      on_death: `query.last_hit_by_player ? ${entity.dropsXP} : 0`
    };
  }

  if (entity.knockback) {
    components['minecraft:knockback_resistance'] = {
      value: parseFloat(entity.knockbackResist) || 0
    };
  }

  return {
    format_version: '1.18.10',
    'minecraft:entity': {
      description: {
        identifier: id,
        is_spawnable: entity.isSpawnable !== false,
        is_summonable: true,
        is_experimental: false
      },
      component_groups: {},
      components,
      events: {}
    }
  };
}

// ── RECIPES ────────────────────────────────────────────────────────────────

function generateRecipeBP(recipe, namespace) {
  const id = resolveId(recipe.identifier, namespace);

  if (recipe.type === 'shaped') {
    const grid = recipe.pattern || [['','',''],['','',''],['','','']];
    const itemToKey = {};
    const key = {};
    const letters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
    let idx = 0;

    for (const row of grid) {
      for (const cell of row) {
        const c = (cell || '').trim();
        if (c && !itemToKey[c]) {
          itemToKey[c] = letters[idx++];
          key[itemToKey[c]] = { item: c };
        }
      }
    }

    const pattern = grid.map(row =>
      row.map(cell => {
        const c = (cell || '').trim();
        return c ? itemToKey[c] : ' ';
      }).join('')
    );

    // Trim trailing empty rows
    let last = -1;
    for (let i = pattern.length - 1; i >= 0; i--) {
      if (pattern[i].trim()) { last = i; break; }
    }
    const trimmedPattern = last >= 0 ? pattern.slice(0, last + 1) : [' '];

    return {
      format_version: '1.17.41',
      'minecraft:recipe_shaped': {
        description: { identifier: id },
        tags: ['crafting_table'],
        pattern: trimmedPattern,
        key,
        result: {
          item: recipe.result || 'minecraft:air',
          count: parseInt(recipe.resultCount) || 1
        }
      }
    };

  } else if (recipe.type === 'shapeless') {
    const ingredients = (recipe.ingredients || []).filter(i => (i || '').trim());
    return {
      format_version: '1.17.41',
      'minecraft:recipe_shapeless': {
        description: { identifier: id },
        tags: ['crafting_table'],
        ingredients: ingredients.map(item => ({ item })),
        result: {
          item: recipe.result || 'minecraft:air',
          count: parseInt(recipe.resultCount) || 1
        }
      }
    };

  } else if (recipe.type === 'smelting') {
    return {
      format_version: '1.17.41',
      'minecraft:recipe_furnace': {
        description: { identifier: id },
        tags: [recipe.smeltingType || 'furnace'],
        input: { item: recipe.input || 'minecraft:air' },
        output: recipe.result || 'minecraft:air'
      }
    };
  }

  return null;
}

// ── RESOURCE PACK HELPERS ─────────────────────────────────────────────────

function generateTerrainTexture(blocks, namespace) {
  const texture_data = {};
  for (const block of blocks) {
    const id = resolveId(block.identifier, namespace);
    const texName = id.replace(':', '_');
    texture_data[texName] = { textures: `textures/blocks/${texName}` };
  }
  return {
    resource_pack_name: 'pack.name',
    texture_name: 'atlas.terrain',
    padding: 8,
    num_mip_levels: 4,
    texture_data
  };
}

function generateItemTexture(items, namespace) {
  const texture_data = {};
  for (const item of items) {
    const id = resolveId(item.identifier, namespace);
    const texName = id.replace(':', '_');
    texture_data[texName] = { textures: `textures/items/${texName}` };
  }
  return {
    resource_pack_name: 'pack.name',
    texture_name: 'atlas.items',
    texture_data
  };
}

function generateLangFile(items, blocks, entities, namespace) {
  const lines = [];
  for (const item of items) {
    const id = resolveId(item.identifier, namespace);
    lines.push(`item.${id}.name=${item.displayName || item.identifier}`);
  }
  for (const block of blocks) {
    const id = resolveId(block.identifier, namespace);
    lines.push(`tile.${id}.name=${block.displayName || block.identifier}`);
  }
  for (const entity of entities) {
    const id = resolveId(entity.identifier, namespace);
    lines.push(`entity.${id}.name=${entity.displayName || entity.identifier}`);
  }
  return lines.join('\n');
}

// ── SYNTAX HIGHLIGHTING ────────────────────────────────────────────────────

function syntaxHighlight(json) {
  if (typeof json !== 'string') {
    json = JSON.stringify(json, null, 2);
  }
  return json
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(
      /("(\\u[a-zA-Z0-9]{4}|\\[^u]|[^\\"])*"(\s*:)?|\b(true|false|null)\b|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)/g,
      match => {
        let cls = 'json-num';
        if (/^"/.test(match)) {
          cls = /:$/.test(match) ? 'json-key' : 'json-str';
        } else if (/true|false/.test(match)) {
          cls = 'json-bool';
        } else if (/null/.test(match)) {
          cls = 'json-null';
        }
        return `<span class="${cls}">${match}</span>`;
      }
    );
}
